In [3]:
import pandas as pd

df = pd.read_pickle("data/selected_uniform_25.pkl")
len(df)

25

In [4]:
df

    filename   interestingness_label
0   0211.jpg         Not Interesting
1   0881.jpg         Not Interesting
2   0462.jpg         Not Interesting
3   0462.jpg         Not Interesting
4   0462.jpg         Not Interesting
5   0754.jpg    Slightly Interesting
6   0044.jpg    Slightly Interesting
7   0047.jpg    Slightly Interesting
8   0129.jpg    Slightly Interesting
9   0602.jpg    Slightly Interesting
10  0149.jpg  Moderately Interesting
11  0733.jpg  Moderately Interesting
12  0793.jpg  Moderately Interesting
13  0858.jpg  Moderately Interesting
14  0523.jpg  Moderately Interesting
15  0852.jpg        Very Interesting
16  0928.jpg        Very Interesting
17  0564.jpg        Very Interesting
18  0842.jpg        Very Interesting
19  0818.jpg        Very Interesting
20  0821.jpg   Extremely Interesting
21  0839.jpg   Extremely Interesting
22  0839.jpg   Extremely Interesting
23  0821.jpg   Extremely Interesting
24  0839.jpg   Extremely Interesting

In [7]:
df_ci = pd.read_pickle("data/df_common_machine_int.pkl")
len(df_ci)

1000

In [8]:
df_ci

,interestingness_value,img_path,ci_score,explanation_appearance
img_id,,,,
1,1.32,/nasdata/OpenImagesV7/train/41180264cfe0bffa.jpg,0.011470,This image shows four people smiling and posin...
2,1.53,/nasdata/OpenImagesV7/train/5c685e499e6f284c.jpg,0.011470,The image shows a panel of four individuals se...
3,1.24,/nasdata/OpenImagesV7/train/d7f8321325bb0a79.jpg,0.011470,A man in formal attire is standing and writing...
4,1.49,/nasdata/OpenImagesV7/train/80e5daa293c6a5bb.jpg,0.011470,The image shows a group of people gathered out...
5,1.31,/nasdata/OpenImagesV7/train/8d653fbb5149aebc.jpg,0.011470,"Three individuals are in a formal setting, wit..."
...,...,...,...,...
996,1.89,/nasdata/flickrUserData/64038177@N08/fav/50134...,0.666319,This image shows a weathered concrete structur...
997,2.32,/nasdata/flickrInt/2021-10-11/51573743710.jpg,0.666319,The image shows a tranquil scene of swans on a...
998,2.12,/nasdata/flickrInt/2023-04-30/52858794854.jpg,0.666319,The image shows a scenic view of trees surroun...
999,2.05,/nasdata/flickrUserData/195472747@N06/fav/5278...,0.666319,"The image depicts a serene, misty forest scene..."
1000,1.83,/nasdata/flickrInt/2022-01-20/51831724118.jpg,0.666319,The image shows a serene wetland scene with le...

In [10]:
df_pers = pd.read_pickle("data/df_generated-personas-sample.pkl")
len(df_pers)

100

In [11]:
df_pers

,age,gender,country,continent,job_branch,mental_workload,emotion
id,,,,,,,
2255,65 or older,male,Nigeria,Africa,Recreational Participant,high,fear
1055,40-44,male,Uganda,Africa,Arts and Entertainment,low,disgust
3406,60-64,male,Venezuela,South America,Media and Communication,low,sad
5244,65 or older,female,Luxembourg,Europe,Recreational Participant,extreme,anger
4254,30-34,female,Namibia,Africa,Sports and Fitness,extreme,amuesement
...,...,...,...,...,...,...,...
7844,35-39,female,Argentina,South America,Sports and Fitness,low,disgust
8877,55-59,diverse,Kenya,Africa,Administration and Clerical,extreme,contentement
9332,35-39,male,United Kingdom,Europe,Energy and Utilities,low,awe
8700,20-24,male,Palestine,Asia,Administration and Clerical,moderate,anger
4205,65 or older,diverse,Spain,Europe,Caregiver,high,awe

In [4]:
import pickle

with open("gdv_500_0\gdv.pkl", "rb") as f:
    data = pickle.load(f)

type(data)

dict

In [5]:
data.keys()

dict_keys(['sorted_layers', 'layer_data', 'gdv_per_layer', 'gdv_per_layer_cosine', 'meta'])

In [7]:
data["meta"]

{'labels': ['Slightly Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Slightly Interesting',
  'Moderately Interesting',
  'Moderately Interesting',
  'Moderately Interesting'],
 'total_layers': 82,
 'max_gdv_layer': 'language_0_D5120',
 'language_first_token_used': 22128,
 'language_mean_fallback_used': 0,
 'dropped_labels_lt_10pct': [np.str_('Extremely Interesting'),
  np.str_('Not Interesting'),
  np.str_('Very Interesting')],
 'kept_labels_ge_10pct': [np.str_('Moderately Interesting'),
  np.str_('Slightly Interesting')],
 'best_umap_by_layer': {'vision_0_D1408': {'tag': 'UMAP_n15__md0.1__cosine__nc2',
   'setup': {'algo': 'UMAP',
    'n_neighbors': 15,
    'min_dist': 0.1,
    'metric': 'cosine',
    'n_components': 2},
   'trustworthiness': 0.8181229017093081,
   'silhouette_on_2D': 0.003441190579906106,
   'plot': 'results/gdv_500_0/plots/vision/vision_0__D=1408_/UMAP/UMAP_n15__md0.1__cosine__nc2.png',
   'coords_csv': 'results/gdv_500_0/plots/vision/vision_0__D=1408_/UMAP/UMAP_n15__md0.1__cosine__nc2__coords.csv',
   'coords': array([[ 6.568667  , 11.090151  ],
          [ 6.3203893 ,  9.929896  ],
          [ 5.9738717 , 13.806507  ],
          [-0.1160182 ,  7.429486  ],
          [ 6.383028  , 10.654402  ],
          [ 0.7034719 ,  7.1297364 ],
          [ 2.0308053 , 11.595787  ],
          [ 3.0523021 , 11.930768  ],
          [ 5.9576526 , 12.327578  ],
          [ 1.2242172 ,  8.893394  ],
          [ 1.3926739 , 10.481652  ],
          [ 0.71636176,  9.245096  ],
          [ 6.9613743 , 11.043805  ],
          [ 8.251441  , 12.975727  ],
          [ 0.7523181 ,  7.8914237 ],
          [ 1.0156438 ,  6.647556  ],
          [ 5.984078  ,  9.907318  ],
          [ 6.2130857 , 12.586737  ],
          [ 1.496846  ,  7.8905954 ],
          [ 7.6769285 , 11.619884  ],
          [ 6.538992  , 13.161732  ],
          [ 6.831241  , 14.305162  ],
          [ 4.2438307 ,  9.0633745 ],
          [ 2.7255642 , 12.068198  ],
          [ 5.9277334 , 11.516487  ],
          [ 5.0107594 , 12.647527  ],
          [ 0.5357252 ,  7.7217374 ],
          [ 6.6952376 , 13.142826  ],
          [ 0.38553303,  7.5193563 ],
          [ 3.2070763 , 12.270733  ],
          [ 1.1601293 ,  7.9086723 ],
          [ 6.4191637 , 11.0030985 ],
          [ 7.9887986 , 11.262168  ],
          [ 6.6353946 , 13.786127  ],
          [ 5.4877334 , 10.197508  ],
          [ 4.4885144 , 10.4557705 ],
          [ 0.36121705,  9.303417  ],
          [ 3.2932694 , 12.140658  ],
          [ 3.708671  , 12.372314  ],
          [ 3.2393758 ,  9.203197  ],
          [ 6.734957  , 13.214347  ],
          [ 5.841369  , 10.390408  ],
          [ 8.426033  , 12.843843  ],
          [ 2.8853693 ,  8.61289   ],
          [ 1.0623528 ,  8.838139  ],
          [ 6.0766716 , 12.549985  ],
          [ 6.5511985 , 10.344165  ],
          [ 0.91828495,  7.621114  ],
          [ 0.9118576 ,  8.93156   ],
          [ 8.34634   , 12.997656  ],
          [ 5.490445  ,  9.707697  ],
          [ 1.6096613 ,  7.9633203 ],
          [ 1.1577188 ,  6.7312055 ],
          [ 4.5933986 , 10.468511  ],
          [ 1.4129759 , 11.030844  ],
          [ 5.768299  ,  9.81542   ],
          [ 1.3367261 , 10.375892  ],
          [ 1.1963799 ,  6.9437366 ],
          [ 8.582005  , 13.232185  ],
          [ 5.772693  ,  9.881346  ],
          [ 1.1311439 , 10.027146  ],
          [ 1.9611834 , 11.480127  ],
          [ 6.4179325 , 13.141259  ],
          [ 0.3720038 ,  8.597551  ],
          [ 6.599663  , 14.383189  ],
          [ 6.831628  , 14.056904  ],
          [ 4.364799  ,  9.10722   ],
          [ 6.9276466 , 12.753275  ],
          [ 8.052068  , 11.071937  ],
          [ 3.4702961 ,  9.404597  ],
          [ 4.192961  , 12.046622  ],
          [ 3.1156976 , 12.28583   ],
          [ 5.920352  ,  9.919872  ],
          [ 6.5491557 , 13.957134  ],
          [ 6.5785484 , 12.768625  ],
          [ 6.207133  , 10.424479  ],
          [ 1.4702218 , 11.238078  ],
          [ 6.8437934 , 11.941588  ],
          [ 6.298042  , 13.617455  ],
          [ 7.1785007 , 13.816323  ],
          [ 1.2767597 ,  8.75176   ],
          [ 5.547994  , 10.394272  ],
          [ 1.7840779 ,  7.810149  ],
          [ 3.9269748 ,  8.820378  ],
          [ 6.7156873 , 12.674929  ],
          [ 6.375891  , 13.267234  ],
          [ 1.3844221 , 11.081515  ],
          [ 8.367379  , 12.750717  ],
          [ 6.865819  , 14.253213  ],
          [ 7.9693384 , 11.27292   ],
          [ 7.1192875 , 13.085671  ],
          [ 8.169029  , 12.954731  ],
          [ 0.42607838,  8.21755   ],
          [ 6.2205424 , 12.372656  ],
          [ 1.2806736 ,  7.9427156 ],
          [ 6.6170855 , 11.572589  ],
          [ 2.2927482 , 11.734054  ],
          [ 8.282425  , 13.295108  ],
          [ 0.39184693,  8.608519  ],
          [ 7.2060385 , 11.052128  ],
          [ 7.2934246 , 12.183664  ],
          [ 6.387443  , 10.551046  ],
          [ 5.9479437 , 12.722646  ],
          [ 7.5421333 , 13.559598  ],
          [ 0.5674338 ,  7.3447294 ],
          [ 5.9643207 , 10.523176  ],
          [ 0.52807385,  7.808099  ],
          [ 5.378774  , 10.785462  ],
          [ 5.14944   , 10.690009  ],
          [ 6.8189263 , 12.075862  ],
          [ 0.90524477,  8.123747  ],
          [ 0.59415615,  8.779361  ],
          [ 0.8276105 ,  6.85221   ],
          [ 1.093698  ,  9.990515  ],
          [ 0.7198804 ,  7.0679145 ],
          [ 6.7053127 , 11.927745  ],
          [ 5.9863615 , 12.00507   ],
          [ 1.6402006 ,  9.108893  ],
          [ 0.4497299 ,  9.005048  ],
          [ 5.834071  , 12.6910305 ],
          [ 5.919272  , 10.688768  ],
          [ 6.136086  , 12.373405  ],
          [ 4.994965  ,  9.431189  ],
          [ 1.1903456 ,  7.8563104 ],
          [ 6.9082956 , 13.967724  ],
          [ 1.3098583 , 10.211536  ],
          [-0.28144574,  7.507135  ],
          [ 6.095597  , 10.1138    ],
          [ 5.968176  , 10.890957  ],
          [ 3.3358011 , 11.9210205 ],
          [ 7.505792  , 13.590875  ],
          [ 8.09306   , 13.017886  ],
          [ 1.0196313 ,  9.093645  ],
          [ 6.303456  ,  9.723514  ],
          [ 6.248203  , 12.773695  ],
          [ 3.344113  , 11.29537   ],
          [ 3.5700853 , 12.2721    ],
          [ 8.680077  , 13.059062  ],
          [ 1.3262587 ,  8.087863  ],
          [ 0.17346165,  7.497987  ],
          [ 0.88120776,  8.481745  ],
          [ 0.93435484,  9.020059  ],
          [ 1.2925838 ,  9.421337  ],
          [ 6.3179913 , 12.959476  ],
          [ 6.059325  , 10.993463  ],
          [ 5.168571  , 11.277568  ],
          [ 7.25487   , 12.920537  ],
          [ 0.51620835,  8.243139  ],
          [ 4.3167553 ,  9.212517  ],
          [ 1.2371294 ,  7.5114594 ],
          [ 8.3169365 , 12.609934  ],
          [ 0.88162553,  6.889209  ],
          [ 0.57552826,  7.5189986 ],
          [ 1.5595825 ,  7.8444715 ],
          [ 7.9686375 , 12.625638  ],
          [ 5.359107  , 10.37709   ],
          [ 6.1127477 ,  9.730888  ],
          [ 1.4048061 ,  9.772115  ],
          [ 1.5848746 ,  7.949209  ],
          [ 6.9115453 , 12.014476  ],
          [ 5.7441306 , 12.233568  ],
          [ 8.250957  , 12.86082   ],
          [ 7.1243343 , 13.947651  ],
          [ 3.9016852 , 12.179733  ],
          [ 7.987906  , 11.257748  ],
          [ 5.8726997 , 12.464645  ],
          [ 7.977437  , 11.2140875 ],